CREATE TABLE PRODUCTS(
	ID INT,
	NAME VARCHAR(500),
	BASE_PRICE DECIMAL(10,2),
	CATEGORY VARCHAR(500),
	BRAND VARCHAR(1000),
	STOCK_QUANTITY INT,
	CREATED_ON TIMESTAMP,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY PRODUCT_ID_PK (ID)
);

CREATE SEQUENCE PRODUCT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PRICING_RULES (
	ID INT,
	NAME VARCHAR(500),
	RULE_TYPE ENUM("percentage discount", "flat discount","bulk pricing","category promotion"),
	VALUE DECIMAL(10,2),
	PRIORITY SMALLINT,
	CONDITION_JSON JSON,
	IS_ACTIVE VARCHAR(1),
	PRIMARY KEY PRICING_RULES_PK (ID)
);

CREATE SEQUENCE PRICING_RULES_ID_SEQ START WITH 1 INCREMENT BY 1;